# Generated by Django 5.0.1 on 2024-02-07 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0002_alter_conversation_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='is_read',
        ),
        migrations.AddField(
            model_name='conversation',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
