# Generated by Django 5.0.1 on 2024-02-07 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0003_remove_message_is_read_conversation_is_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='is_read',
        ),
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
