# Generated by Django 5.0.1 on 2024-01-13 11:40

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='imagem',
            field=models.ImageField(blank=True, upload_to=accounts.models.user_profile_image_path),
        ),
    ]
