# Generated by Django 5.0.1 on 2024-01-13 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profileuser_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileuser',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
